name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v7

      - name: Instalar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Instalar Surge
        run: npm install --global surge

      - name: Desplegar en Surge
        run: surge ./ parcial1-electiva2-Angel-Gonzalez-20251122.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
